### ISSUE TITLE
upload.get_approved_upload_method() - FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by melkimble** [mytardis/mydata-python#121]
Same error through command line or python and same source. Running on Windows 10 Pro version 20H2 19042.867. Uploading seems to be hung up on "DEFAULT_CREATION_FLAGS" when get_approved_upload_method() is called. Not sure if it's subprocess+windows related: 
https://stackoverflow.com/questions/39269675/python-trouble-with-popen-filenotfounderror-winerror-2
https://stackoverflow.com/questions/42572582/winerror-2-the-system-cannot-find-the-file-specified-python

From python:
```
from mydata.commands import upload
upload.get_approved_upload_method()
Checking for approved upload method...
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\GitHub\mytardis-mydata-parser\mytardis-mydata-parser-env\lib\site-packages\mydata_python-0.0.1-py3.6.egg\mydata\commands\upload.py", line 113, in get_approved_upload_method
    upload_via_staging_request = settings.uploader.request_staging_access()
  File "D:\GitHub\mytardis-mydata-parser\mytardis-mydata-parser-env\lib\site-packages\mydata_python-0.0.1-py3.6.egg\mydata\models\uploader.py", line 333, in request_staging_access
    self.upload_to_staging_request = self.existing_upload_to_staging_request()
  File "D:\GitHub\mytardis-mydata-parser\mytardis-mydata-parser-env\lib\site-packages\mydata_python-0.0.1-py3.6.egg\mydata\models\uploader.py", line 283, in existing_upload_to_staging_request
    + urllib.parse.quote(self.ssh_key_pair.fingerprint)
  File "D:\GitHub\mytardis-mydata-parser\mytardis-mydata-parser-env\lib\site-packages\mydata_python-0.0.1-py3.6.egg\mydata\utils\openssh.py", line 205, in fingerprint
    self._fingerprint, self.key_type = self.read_fingerprint_and_key_type()
  File "D:\GitHub\mytardis-mydata-parser\mytardis-mydata-parser-env\lib\site-packages\mydata_python-0.0.1-py3.6.egg\mydata\utils\openssh.py", line 180, in read_fingerprint_and_key_type
    creationflags=DEFAULT_CREATION_FLAGS,
  File "C:\Python\Python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\Python\Python36\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

From command line:
```
(mytardis-mydata-env) D:\GitHub\mytardis-mydata-parser\mydata-python>mydata upload -v

Using MyData configuration in: C:\ProgramData\Monash University\MyData\MyData.cfg

Scanning D:\GitHub\mytardis-mydata-parser/NGS_Outputs/Parsed/ using the "User Group / Dataset" folder structure...

Checking for approved upload method...

Traceback (most recent call last):
  File "D:\GitHub\mytardis-mydata-parser\mytardis-mydata-parser-env\Scripts\mydata-script.py", line 33, in <module>
    sys.exit(load_entry_point('mydata-python==0.0.1', 'console_scripts', 'mydata')())
  File "D:\GitHub\mytardis-mydata-parser\mytardis-mydata-parser-env\lib\site-packages\mydata_python-0.0.1-py3.6.egg\mydata\client.py", line 33, in run
    entry_point()
  File "D:\GitHub\mytardis-mydata-parser\mytardis-mydata-parser-env\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\GitHub\mytardis-mydata-parser\mytardis-mydata-parser-env\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\GitHub\mytardis-mydata-parser\mytardis-mydata-parser-env\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\GitHub\mytardis-mydata-parser\mytardis-mydata-parser-env\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\GitHub\mytardis-mydata-parser\mytardis-mydata-parser-env\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\GitHub\mytardis-mydata-parser\mytardis-mydata-parser-env\lib\site-packages\mydata_python-0.0.1-py3.6.egg\mydata\commands\upload.py", line 158, in upload_cmd
    upload_method = get_approved_upload_method()
  File "D:\GitHub\mytardis-mydata-parser\mytardis-mydata-parser-env\lib\site-packages\mydata_python-0.0.1-py3.6.egg\mydata\commands\upload.py", line 113, in get_approved_upload_method
    upload_via_staging_request = settings.uploader.request_staging_access()
  File "D:\GitHub\mytardis-mydata-parser\mytardis-mydata-parser-env\lib\site-packages\mydata_python-0.0.1-py3.6.egg\mydata\models\uploader.py", line 333, in request_staging_access
    self.upload_to_staging_request = self.existing_upload_to_staging_request()
  File "D:\GitHub\mytardis-mydata-parser\mytardis-mydata-parser-env\lib\site-packages\mydata_python-0.0.1-py3.6.egg\mydata\models\uploader.py", line 283, in existing_upload_to_staging_request
    + urllib.parse.quote(self.ssh_key_pair.fingerprint)
  File "D:\GitHub\mytardis-mydata-parser\mytardis-mydata-parser-env\lib\site-packages\mydata_python-0.0.1-py3.6.egg\mydata\utils\openssh.py", line 205, in fingerprint
    self._fingerprint, self.key_type = self.read_fingerprint_and_key_type()
  File "D:\GitHub\mytardis-mydata-parser\mytardis-mydata-parser-env\lib\site-packages\mydata_python-0.0.1-py3.6.egg\mydata\utils\openssh.py", line 180, in read_fingerprint_and_key_type
    creationflags=DEFAULT_CREATION_FLAGS,
  File "C:\Python\Python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\Python\Python36\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by dyakhnov** [comment]
Hi Melissa,

MyData CLI has been build to mainly be run on Linux OSes, but yesterday I had to run it on Windows and discovered that resources folder is missing (I think to slim installation on Linux), therefore added missing files and managed to run it on (64-bit) Windows 10.

Try to update your code from GitHub and run again.

Cheers,
Dmitry.

**Comment by melkimble** [comment]
Thanks Dmitry! Works with run.py for upload, scan, and config (e.g., `run.py upload -v`) on Win10 64-bit. Error persists if using `mydata` command after running `setup.py install`. There are also missing `__init__.py` files in `mydata-python/mydata/indexing` and `mydata-python/mydata/indexing/models`. 

Melissa
